---
# This playbook deploys a kubernetes cluster with the default addons.

- hosts: all
  roles:
    - yum-repo
  tags:
    - yum-repo

# install ssl cert
- hosts: sslhost
  roles:
     -  sslcert
  tags:
     -  sslcert

# Install etcd
- hosts: etcd
  roles:
   -   etcd
  tags:
    - etcd

# Install docker
- hosts: all
  when: use_containerd == "false"
  roles:
    - docker
  tags:
    - docker

# install containerd
- hosts: all
  when: use_containerd == "true"
  roles:
    - containerd
  tags:
    - containerd

# install haproxy
- hosts: masters
  roles:
    - haproxy
  tags:
    - haproxy

# install kubernetes master services
- hosts: masters
  roles:
    - master
  tags:
    - master

# install kubernetes on the nodes
- hosts: node
  roles:
    - node
  tags:
    - node
