---
# This playbook deploys a kubernetes cluster with the default addons.

# Install yum-repo
- hosts: all
  roles:
    - role: yum-repo
      when: ansible_os_family == "RedHat"
  tags:
    - yum-repo

# Install sslcert
- hosts: sslhost
  roles:
    - role: sslcert 
  tags:
    - sslcert

# Install etcd
- hosts: etcd
  roles:
    - role: etcd
  tags:
    - etcd

# Install container runtime
- hosts: all
  roles:
    - { role: docker, when: use_containerd == 'false' }
    - { role: containerd, when: use_containerd == 'true' }
  tags:
    - runtime

# install haproxy
- hosts: masters
  roles:
    - role: haproxy
  tags:
    - haproxy

# install keepalived
- hosts: masters
  roles:
    - role: keepalived
  tags:
    - keepalived

# install kubernetes master services
- hosts: masters
  roles:
    - role: master
  tags:
    - master

# install kubernetes on the nodes
- hosts: node
  roles:
    - role: node
  tags:
    - node
