---
- name: reload systemd
  command: systemctl --system daemon-reload

- name: restart docker
  command: /bin/true
  notify:
    - stop docker
    - start docker

- name: start docker
  command: /bin/true
  notify:
    - docker start service

- name: stop docker
  service: name=docker state=stopped

- name: docker start service
  service: name=docker state=started
