---
- name: Install etcd
  when: ansible_os_family == "RedHat"
  yum:
    name: etcd
    state: latest

- name: Create etcd config directory
  file: path={{ etcd_conf_dir }} state=directory

- name: Write etcd config file
  template: src=etcd.conf.j2 dest=/etc/etcd/etcd.conf
  register: etc_config

- name: Enable and start etcd
  when: etc_config|succeeded
  service: name=etcd enabled=yes state=started

- name: Retart etcd
  service: name=etcd state=restarted
  when: etc_config|changed
  register: etcd_started
