---
- name: Install flannel
  when: flannel
  yum:
    name: flannel-0.5.3-9
    state: latest
    update_cache: yes

- name: update flannel config
  template: src="flanneld.j2" dest={{ flannel_dir }}/flanneld
  register: change_flannel

- name: Generate etcd configuration for etcd
  template:
    src: "flannel-config.json"
    dest: "/tmp/config.json"

- name: Insert flannel configuration into etcd
  when: etcd_peer_url_scheme == 'https'
  command: 'curl -L --cacert "{{ etcd_peer_ca_file }}" --cert "{{ etcd_peer_cert_file }}" --key "{{ etcd_peer_key_file }}" "{{ etcd[0] }}/v2/keys{{ flannel_key }}/config" -XPUT --data-urlencode value@/tmp/config.json'

- name: Insert flannel configuration into etcd
  when: etcd_peer_url_scheme == 'http'
  command: 'curl -L "{{ etcd[0] }}/v2/keys{{ flannel_key }}/config" -XPUT --data-urlencode value@/tmp/config.json'

- name: move flannel env for docker 
  command: mv /usr/lib/systemd/system/docker.service.d /usr/lib/systemd/system/docker-latest.service.d

- name: copy etcd certificate from ansible host
  when: etcd_peer_url_scheme == 'https'
  copy: src={{ master_cert_dir }} dest={{ kube_config_dir }}
  register: etcd_cert

- name: start and enable flannel on node
  when: change_flannel|succeeded
  service: name=flanneld enabled=no state=started

- name: reload flanneld
  when: change_flannel|changed or etcd_cert|changed
  service: name=flanneld state=restarted
