---
- name: Install flannel
  when: flannel
  yum:
    name: flannel
    state: latest
    update_cache: yes

- name: update flannel config
  template: src="flanneld.j2" dest={{ flannel_dir }}/flanneld
  register: change_flannel

#- name: update etcd
#  command: etcdctl mk {{ flannel_key }} '{"Network": "10.10.0.0/16", "SubnetLen": 24, "Backend": { "Type": "vxlan", "VNI": 1 } }'
#  when: change_flannel|changed
#  register: etcd_add

- name: move flannel env for docker 
  command: mv /usr/lib/systemd/system/docker.servive.d /usr/lib/systemd/system/docker-latest.servive.d

- name: copy etcd certificate from ansible host
  when: etcd_peer_url_scheme == 'https'
  copy: src={{ master_cert_dir }} dest={{ kube_config_dir }}
  register: etcd_cert

- name: start and enable flannel on node
  when: change_flannel|succeeded
  service: name=flanneld enabled=no state=started

- name: reload flanneld
  when: change_flannel|changed or etcd_cert|changed
  service: name=flanneld state=restarted
