---
- name: Copy kubelet.yaml
  template:
    src: kubelet.yaml.j2
    dest: "{{ kube_config_dir }}/kubelet.yaml"

- name: Copy kubelet.conf
  template:
    src: kubelet.conf.j2
    dest: "{{ kube_config_dir }}/kubelet.conf"

- name: Restart kubelet after config changes
  service:
    name: kubelet
    state: restarted
